### ISSUE TITLE
Vendor is not able to access dashboard 

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#10]
https://watch.screencastify.com/v/8oFZV6ZT7b8d4fngeGMR

**Comment by cool-raju** [comment]
no such issue
here is the video 
https://www.loom.com/share/a52a2560b7ff46e4af891a0949801f32
please select right dashboard page from Vendor Dashboard Page

 under settings -> general tab
Thanks

**Comment by moumitahalder** [comment]
@dashbaord page is set with right shortcode [mvx_vendor]

Check this page : http://wcmpdemos.com/elementor/dashboard/
uname wcmp_vendor
pwd wcmp_vendor

**Comment by cool-raju** [comment]
m talking about https://scrnli.com/Jnp3J67V28w2Km this section

**Comment by cool-raju** [comment]
please check

**Comment by moumitahalder** [comment]
You are right @cool-raju

**Comment by moumitahalder** [comment]
But, whenever the plugin is installed we should set the corresponding dashboard and registration page with it's endpoint.

**Comment by moumitahalder** [comment]
Like previous version

**Comment by cool-raju** [comment]
yes, we will do it. @abhirup97 please look into this.
