### ISSUE TITLE
Upgrade to pro text

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#113]
https://prnt.sc/1PxPuUslMXTn

**Comment by cool-raju** [comment]
@C0ntent please look into this

**Comment by cool-raju** [comment]
any update ???? @C0ntent...What should I change here? please reply asap

**Comment by C0ntent** [comment]
Raju- da apologies did not see this earlier. Will work on it right away.

Regards
Neda

**Comment by moumitahalder** [comment]
@C0ntent ????

**Comment by cool-raju** [comment]
is this fixed? right??
