### ISSUE TITLE
Display action name on hover

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#123]
User will not have any idea what to do with this icon : https://watch.screencastify.com/v/03jZ3nVU9ERori9349wo

**Comment by cool-raju** [comment]
need to add CSS

**Comment by cool-raju** [comment]
fixed

**Comment by cool-raju** [comment]
not fixed

**Comment by cool-raju** [comment]
workboard section icons hover not working @Biplab-Samanta

**Comment by moumitahalder** [comment]
@Biplab-Samanta check all the icons. Only Edit hover is working

**Comment by cool-raju** [comment]
@Biplab-Samanta have you checked it?
