### ISSUE TITLE
Coding issue

### ISSUE THREAD

**Issue by purnendudash** [multivendorx/mvx#130]
https://github.com/wcmarketplace/MultivendorX/blob/f0377f9a76ec8bf10fc365ab43a6446ab9da9342/admin/class-mvx-settings.php#L172

1. Why the name is like this? - mvx_headding3
2. Why the text domain is still "dc-woocommerce-multi-vendor"

**Comment by purnendudash** [comment]
Also kindly clean the code from 19 - 84 line.

**Comment by cool-raju** [comment]
so what will be d updated text-domain??? @purnendudash
