### ISSUE TITLE
regenerate commission is keeping old commission

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#133]
https://prnt.sc/BdZy6cPj363E

**Comment by cool-raju** [comment]
no such issue found

**Comment by moumitahalder** [comment]
Here is the full video : https://watch.screencastify.com/v/ZBOVvZIM5GCb9eqJLfLM

**Comment by moumitahalder** [comment]
As you can see now the old commission is deleted.  However, the commission is not recalculating properly.

**Comment by cool-raju** [comment]
fixed
