### ISSUE TITLE
when migrating from WCMp to MVX, migration issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#135]
- Settings like product capability, commission etc :  https://watch.screencastify.com/v/UwyQ3gyRk6zpxJYlecqn

**Comment by moumitahalder** [comment]
To cjeck use this site https://wcmpdemos.com/migration/wp-admin/admin.php?page=mvx#&submenu=settings&name=products-capability

**Comment by moumitahalder** [comment]
Now vendor has add product capability, but vendor dashboard is not showing that : https://watch.screencastify.com/v/4QidlzhfYc8pSpiWp9rA

**Comment by cool-raju** [comment]
issue resolved
