### ISSUE TITLE
Double commission Issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#139]
**To Recreate**
- Delete a suborder
- - Regenerate sub order from main order
- check the commission page.
- You can see the old commission and new commission
- https://watch.screencastify.com/v/2HuI05PD6amc0Dp8GHnf

**Comment by cool-raju** [comment]
please check your suborder is deleted or in trashed

**Comment by moumitahalder** [comment]
The suborder is in trash, but not permanently deleted. that is why this issue.

**Comment by cool-raju** [comment]
commission will deleted whenever related suborder will be deleter

**Comment by cool-raju** [comment]
if this flow need to change, then please let me know

**Comment by moumitahalder** [comment]
Let me think

**Comment by cool-raju** [comment]
fixed
