### ISSUE TITLE
Analytics Issue 

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#141]
No Data under ledger board issue
https://prnt.sc/mZZ3MiqR9_UU

**Comment by cool-raju** [comment]
data is showing in my end https://scrnli.com/gKLiHvQP8QNSMy

**Comment by moumitahalder** [comment]
Check here http://wcmpdemos.com/elementor/wp-admin/admin.php?page=mvx#&submenu=analytics&name=admin-overview

**Comment by cool-raju** [comment]
discussed

**Comment by moumitahalder** [comment]
- All other fields such as Performance, Charts are taking data of the last 7 days by default. 
But the Leaderboards is not taking any data unless you are setting that via datepicker.

**Comment by cool-raju** [comment]
fixed
