### ISSUE TITLE
Commission on Tax

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#147]
If Tax option s enabled via WCMp >> Settings >> Payment. 
Then create a new settings "Commission Calculation on Tax"

If this option is enabled, then will not get the full tax amount. WCMp will calculate commission on tax also and then pay only that part.
Example :
Product cost 100
Tax 20
vendor Commission 20%

Now vendor will get 20% of 100 + 20% of 20

**Comment by cool-raju** [comment]
added
