### ISSUE TITLE
Rating Parameters of Review not working in Product page

### ISSUE THREAD

**Issue by aditidualcube** [multivendorx/mvx#149]
to recreate the issue:
1. in ratings & review settings create 2 categories of Rating parameters.
2. create a customer and place a order of any vendor products.
3. now go to the product page and navigate to review tab.

*Categories of Rating parameters is not getting displayed*

video link- https://watch.screencastify.com/v/n58jk2yWsf8aSLfKzjGF

**Comment by cool-raju** [comment]
is the review and rating module active or not??
Please check and let me know

**Comment by cool-raju** [comment]
no update
