### ISSUE TITLE
Shipping by distance values not getting saved in vendor dashboard

### ISSUE THREAD

**Issue by aditidualcube** [multivendorx/mvx#152]
*To recreate the issue*
1.Enable Shipping by distance from Module section of mvx.
2. Now in vendor dashboard select shipping by distance and set the price & click on save.
Here is the video: https://watch.screencastify.com/v/oqEe6Roy05ZNFPKoIJXf

Issue- values of shipping by distance in vendor dashboard is not getting saved

**Comment by cool-raju** [comment]
fixed
