### ISSUE TITLE
Pending Vendor Issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#172]
- Approve Button is not there : https://prnt.sc/VkgA0PiOHoRh
- By default, we should display the Vendor Application tab first (Current FLow https://prnt.sc/p6C7ZApR7VBn) || (Expected Flow https://prnt.sc/vzZJUqRTPthb)
- We should not display other irrelevant tabs like Store, Social, Payment

**Comment by cool-raju** [comment]
added
