### ISSUE TITLE
Shipping note

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#178]
It is better to display text like this, so customers will understand what is a sub order. (Optional settings)

- Checkout Page : https://www.awesomescreenshot.com/image/31309918?key=2d7e84f63f26c8782950145ba5c7590b
Since your order contains products sold by different vendors, it has been split into multiple sub-orders. Each sub-order will be handled by their respective vendor independently.

- Cart page : https://www.awesomescreenshot.com/image/31309957?key=f787bbe6bd502f507d54bb2957207070
The products in your cart are sold by multiple different vendor partners. The order will be placed simultaneously with all vendors and you will receive a package from each of them.

**Comment by user-promi** [comment]
For cart page you need to override the cart.php file (yourtheme/woocommerce/cart/cart.php) with this file https://drive.google.com/file/d/1Ksxkfo1J6lmyyKrCp950cXXKFP1gJGK7/view?usp=share_link and 
for checkout page you need to override the order-details.php file ( yourtheme/woocommerce/order/order-details.php) with this file https://drive.google.com/file/d/1C0DrqnsqcVIofg80PVCnQcjql8j8FQfA/view?usp=share_link 
and also you need to add this code in functions.php file. here is the code - https://drive.google.com/file/d/1YKAb1TN7L68UuCNlvriDIBK3pmIwbvY-/view?usp=share_link
