### ISSUE TITLE
Dashboard New tab

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#187]
a. Add a tab to the menu (left) – Requested Refunds || https://prnt.sc/5CnoewjWOetI
b. Add a tab to the menu (on the left) – Customer Questions || https://prnt.sc/CgeqB7CyqEE2

**Comment by moumitahalder** [comment]
Is it possible to add text to the icon (see photo)? For example Rocket icon and text: Traffic”?

**Comment by moumitahalder** [comment]
https://wc-marketplace.com/support-forum/topic/some-frontend-dashboard-questions-and-a-few-more/#post-141284

**Comment by cool-raju** [comment]
issue resolved

**Comment by cool-raju** [comment]
enhancement added
