### ISSUE TITLE
Change text 

### ISSUE THREAD

**Issue by C0ntent** [multivendorx/mvx#192]
![image](https://user-images.githubusercontent.com/102576696/186179805-fd21cf6a-68a9-49ec-b011-4b652310b371.png)

Add your gateway amount or percentage here.

**Comment by C0ntent** [comment]
Change Content 

![image](https://user-images.githubusercontent.com/102576696/186181226-ff832a24-28f6-4f42-a009-08704b44eb00.png)

**Comment by C0ntent** [comment]
Content for the registration description and format description is similar. This should not be the case
![image](https://user-images.githubusercontent.com/102576696/186181708-7813bf04-a59f-4028-9a95-feb742e74927.png)

**Comment by C0ntent** [comment]
In case my format type is Section ... the lower line of the format option box is not visible
![image](https://user-images.githubusercontent.com/102576696/186182161-cec58300-2bb3-4998-948f-1478021713f8.png)

**Comment by C0ntent** [comment]
Spell Check  - Knowledgebase
![image](https://user-images.githubusercontent.com/102576696/186184197-ae140fcc-6291-4127-aefb-7804289b9ed8.png)

**Comment by amithaldar92** [comment]
![changes](https://user-images.githubusercontent.com/106724845/186193002-de830110-95d8-4e1a-afa4-e444c30a7ae5.png)

**Comment by cool-raju** [comment]
fixed
