### ISSUE TITLE
image changes required

### ISSUE THREAD

**Issue by cool-raju** [multivendorx/mvx#196]

**Comment by cool-raju** [comment]
https://scrnli.com/files/WyySW9hZ573G8u

**Comment by amithaldar92** [comment]
ok

**Comment by cool-raju** [comment]
![template1](https://user-images.githubusercontent.com/54469921/186856638-b869e1e9-0e09-4df5-8a85-c20c2fcd79e4.png)
![template2](https://user-images.githubusercontent.com/54469921/186856643-a3f7c6ac-f49d-489f-ba35-4eba60bfc7cb.png)
![template3](https://user-images.githubusercontent.com/54469921/186856647-8740ff71-391c-4faf-a55e-d6a74715c9d3.png)

**Comment by cool-raju** [comment]
fixed

**Comment by amithaldar92** [comment]
okay
