### ISSUE TITLE
Cannot Add Product Image as Vendor Even though Upload Media Abilities are on

### ISSUE THREAD

**Issue by ghost** [multivendorx/mvx#197]
Error Code (regardless of image size):

The server cannot process the image. This can happen if the server is busy or does not have enough resources to complete the task. Uploading a smaller image may help. Suggested maximum size is 2560 pixels.

**Comment by cool-raju** [comment]
Hi @CrypticCry 
We have checked on our end. We don't face any such issue on our end. Please check this video https://www.loom.com/share/3bb177cc6f0840c1938adae73dac77d7
If you still face this issue then, please share a video so that we can check
Thanks

**Comment by ghost** [comment]
@cool-raju 

Attached is a video showing the process. The first image is a 640 x 427-pixel image. 

https://user-images.githubusercontent.com/93066830/187544390-578fe047-68fa-4479-a2d5-88a6cb007fb6.mp4

**Comment by moumitahalder** [comment]
Hi @CrypticCry ,

This isn’t being caused by the plugin but by WordPress itself. Since version 5.3 WordPress will not allow uploads larger than 2560 pixels.

See this link https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/, for more details.

**Comment by cool-raju** [comment]
hope this issue is fixed
