### ISSUE TITLE
Seller cannot Edit Coupon even though they are Given the Ability to

### ISSUE THREAD

**Issue by ghost** [multivendorx/mvx#198]
When a seller clicks the edit icon for coupons, it loads the same page again without entering the coupon details page.

**Comment by cool-raju** [comment]
Hi @CrypticCry 
We have checked on our end. We don't face any such issue on our end. Please check this video https://www.loom.com/share/3bb177cc6f0840c1938adae73dac77d7
If you still face this issue then, please share a video so that we can check
Thanks

**Comment by cool-raju** [comment]
Hi @CrypticCry 
Which section do you refer? can you please share a screenshot or video
Thanks

**Comment by ghost** [comment]
@cool-raju 

My settings:
![image](https://user-images.githubusercontent.com/93066830/187542066-7a1e63a8-ee2c-415f-87d4-2d1ddba3219c.png)

Pressing edit on a coupon:
https://user-images.githubusercontent.com/93066830/187542330-60c2f1a1-f883-4af5-80db-1da3300d5a0f.mp4

**Comment by cool-raju** [comment]
Hi @CrypticCry,
We have added the fix. Please use our current git version.
After updating the plugin please checked and uncheck one of the product-capability settings ( like the Edit coupon checkbox ). So that capability will update
Thanks

**Comment by cool-raju** [comment]
fixed
