### ISSUE TITLE
Issue on Registration Form 

### ISSUE THREAD

**Issue by tan-hue** [multivendorx/mvx#201]
![image](https://user-images.githubusercontent.com/85879161/187021136-f8693b60-e7d2-47e7-8069-a8101fe40898.png)

Registration issues while using checkboxes. 

![image](https://user-images.githubusercontent.com/85879161/187021166-36c56285-455f-42da-bd20-72dcea8aed7f.png)

**Comment by cool-raju** [comment]
fixed
