### ISSUE TITLE
Installed MultiVendor X - Header Error

### ISSUE THREAD

**Issue by tpaburkhart** [multivendorx/mvx#204]
Hello. I installed MultiVendorX after deactivating all of the old WCMp addons, and am getting the following error now:

`Warning: Cannot modify header information - headers already sent by (output started at /home/customer/www/pantypimpgirls.com/public_html/wp-content/plugins/MultiVendorX-main/includes/mvx-core-functions.php:1) in /home/customer/www/pantypimpgirls.com/public_html/wp-admin/includes/misc.php on line 1381
`

I also can't install any other plugins. My site is totally down now. Any advice, please?

**Comment by cool-raju** [comment]
Hi, @tpaburkhart 
can you please tell us, how many plugins are active right now?

**Comment by tpaburkhart** [comment]
Yes - I attached a screenshot of the active plugins. Also, on the frontend, I'm getting this error: 

`Notice: Trying to get property 'ID' of non-object in /home/customer/www/pantypimpgirls.com/public_html/wp-content/plugins/elementor/core/base/document.php on line 250`

I can't add/delete/reactivate any plugins at all now, either. 

Thank you for the help. 
<img width="1354" alt="Screen Shot 2022-08-30 at 3 33 01 AM" src="https://user-images.githubusercontent.com/112468384/187377281-8d47b5ef-0fc0-4120-83eb-918ef601e6ea.png">

**Comment by tpaburkhart** [comment]
Here are all of the inactive plugins.
<img width="1223" alt="Screen Shot 2022-08-30 at 3 34 56 AM" src="https://user-images.githubusercontent.com/112468384/187377683-97363244-b87e-4bed-afdf-06dce2e0fde4.png">

**Comment by cool-raju** [comment]
Hi,
The error is coming from elementor plugin. Please do check only the woocommerce and multivendorx plugin active first. Then active one by one
Thanks

**Comment by tpaburkhart** [comment]
<img width="1226" alt="Screen Shot 2022-08-30 at 3 41 21 AM" src="https://user-images.githubusercontent.com/112468384/187378991-7527e673-ea0b-447c-a644-021c35a6e421.png">

I dactivated all of my plugins, and my theme, and my child theme… and I'm still getting the error.

**Comment by cool-raju** [comment]
Hi, @tpaburkhart we have fixed the issue. Please check
Thanks

**Comment by tpaburkhart** [comment]
Unfortunately, now I'm getting a white page in the admin area with this error on the top:

`
Warning: Cannot modify header information - headers already sent by (output started at /home/customer/www/pantypimpgirls.com/public_html/wp-content/plugins/MultiVendorX-main/includes/mvx-core-functions.php:1) in /home/customer/www/pantypimpgirls.com/public_html/wp-includes/pluggable.php on line 1421`

**Comment by cool-raju** [comment]
please update the plugin. first delete existing plugin and update with current git plugin

**Comment by tpaburkhart** [comment]
<img width="1318" alt="Screen Shot 2022-08-30 at 3 52 03 AM" src="https://user-images.githubusercontent.com/112468384/187381253-58c12670-20be-44da-aca5-35c29f80ae87.png">

**Comment by tpaburkhart** [comment]
ok - updating

**Comment by tpaburkhart** [comment]
The error is gone now… but, what do I use for a page builder? If I cant use Elementor, I'll have to redesign the entire site.

**Comment by cool-raju** [comment]
now you can activate all your plugins.

**Comment by cool-raju** [comment]
Notice: Trying to get property 'ID' of non-object in /home/customer/www/pantypimpgirls.com/public_html/wp-content/plugins/elementor/core/base/document.php on line 250

This issue is coming from elementor. If you still facing the issue then contact to elementor plugin author. There is no relation with our plugin.
Thanks

**Comment by cool-raju** [comment]
Hi,
Hope this header issue is fixed on your end. If you face any such issue then please don't hesitate to create a new issue
Thanks

**Comment by tpaburkhart** [comment]
Thank you for your help. The header issue is fixed. I'll reach out to Elementor.
