### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by amithaldar92** [multivendorx/mvx#205]
![image](https://user-images.githubusercontent.com/106724845/187378164-1dd0e80f-a375-4a1f-912f-776fb61278ef.png)

**Comment by amithaldar92** [comment]
![image](https://user-images.githubusercontent.com/106724845/187379532-b780ce33-164f-4f75-ac96-ed5c49d6dc84.png)

**Comment by Biplab-Samanta** [comment]
issue fixed with updated css @cool-raju
