### ISSUE TITLE
Transition WPMC MultivendorX

### ISSUE THREAD

**Issue by jensgans** [multivendorx/mvx#210]
Hello, we have been working with WCMP for one client so far. Now that the transition to MultivendorX is imminent, we are wondering whether there will be a safe migration or whether we should switch straight away. On a test environment, the changeover has worked well. What is the timetable for this?

**Comment by moumitahalder** [comment]
Hi @jensgans, if the beta version is working well on your test site, then you can also apply the same for your live site too.

**Comment by jensgans** [comment]
Sorry, there was a typo in my first message. I meant that the transition on our test system did not run without errors. For example, the entries in the vendors list were no longer displayed.

**Comment by cool-raju** [comment]
@jensgans 
We have updated our plugin language files. Please use the updated one from GitHub. if still facing the issue then could you please explain your issue with a video or screenshot
Thanks

**Comment by cool-raju** [comment]
Hi @jensgans 
if you still face the issue, please let us know.
