### ISSUE TITLE
Pro Version

### ISSUE THREAD

**Issue by jensgans** [multivendorx/mvx#211]
Hello, how can we test the Pro version? We need some of the modules.

**Comment by moumitahalder** [comment]
Hi @jensgans, we are yet to release the pro version, Once that will be ready we will share the zip file over mail.

**Comment by jensgans** [comment]
Hello @moumitahalder, thanks for the answer. Do you have any idea about the schedule we are talking about here?

**Comment by moumitahalder** [comment]
Hi @jensgans we are hoping to release this by next week.
