### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#214]
- Stripe

- [ ] When vendor is trying to connect, it is giving us this error : {"error":{"message":"No application matches the supplied client identifier"}}. Although we have configured stripe settings properly : https://watch.screencastify.com/v/IdhmQNkG9TbIwHS7gdFD

- PayPal

**Comment by cool-raju** [comment]
please check whether you have added the redirect link properly on the stripe account @moumitahalder di
Thanks
