### ISSUE TITLE
Resubmit Application is missing 

### ISSUE THREAD

**Issue by tan-hue** [multivendorx/mvx#216]
whenever the admin rejects any particular vendor, the vendors can resubmit their application. this particular function is missing 

![image](https://user-images.githubusercontent.com/85879161/188793587-c0a40576-ad24-48dd-b24f-efdd06524b71.png)

**Comment by cool-raju** [comment]
https://www.loom.com/share/23265937923c46bcb481ed69b887271f
no such error
