### ISSUE TITLE
Add Reject option under workboard>>> taskboard>> pending vendor section

### ISSUE THREAD

**Issue by tan-hue** [multivendorx/mvx#219]
1. Add a Reject option 
2. issues while the vendor tries to resubmit their application from their dashboard

**Comment by cool-raju** [comment]
The reject icon is already there.. https://scrnli.com/files/YQ5YpeZF96Nj79

**Comment by cool-raju** [comment]
@tan-hue

**Comment by cool-raju** [comment]
any update @tan-hue ?? otherwise will close this issue
