### ISSUE TITLE
Uploading Plugin MultiVendor X Bricks the site

### ISSUE THREAD

**Issue by mohammedsaifali** [multivendorx/mvx#222]

**Comment by mohammedsaifali** [comment]
![WhatsApp Image 2022-09-18 at 3 42 42 PM](https://user-images.githubusercontent.com/44836109/190912661-904d0a2e-dfd9-4669-ad0b-8d43c96a4def.jpeg)

**Comment by cool-raju** [comment]
Hi @mohammedsaifali,
please enable debug log and share your log file with us. So that we can check
Thanks

**Comment by mohammedsaifali** [comment]
@cool-raju Email the details to contact

**Comment by cool-raju** [comment]
Hi @mohammedsaifali 
Your filezila access has a write permission issue. We are not able to access your files

**Comment by cool-raju** [comment]
Hi @mohammedsaifali 
any update from your site? Are you still facing an error??? then please share details with write access
Thanks

**Comment by cool-raju** [comment]
hope your issue has been fixed
Thanks
