### ISSUE TITLE
Add Media File option is missing 

### ISSUE THREAD

**Issue by tan-hue** [multivendorx/mvx#223]
add media file option is missing MultiVendorX >> Vendor

![image](https://user-images.githubusercontent.com/85879161/190991593-4526c0f4-63e0-4e73-9eca-f4ba8dcfe082.png)

![image](https://user-images.githubusercontent.com/85879161/190991680-c9f23da2-915f-4851-a15c-8982eb00f384.png)

**Comment by cool-raju** [comment]
this is not possible for our current version. this is already in our r&d section
