### ISSUE TITLE
Vendor cannot upload or edit product

### ISSUE THREAD

**Issue by rafkal3000** [multivendorx/mvx#231]
Why a vendor cannot upload or edit product.

But if am not getting this someone should please helpout

**Comment by cool-raju** [comment]
Hi,
Can you please check your product capability? https://scrnli.com/files/RsozRzBtd3kW5F
if still facing the issue please share a video of your issue. So that we will guide you
Thanks

**Comment by rafkal3000** [comment]
after selecting category below is the message am receiving
"No allowed Product types found. Please contact site administrator."
HAVE SET MY PRODUCT CAPABILITY AND YET IS NOT WORKING

**Comment by cool-raju** [comment]
ok. please go to the module section and enable one of the product types like simple, group, etc https://scrnli.com/files/tuRf8UdFE634Ul
Thanks

**Comment by rafkal3000** [comment]
Where can i get the real file, cause the plugin file I download has a
broken css link which makes the page scattered
[image: image.png]this is how my page is showing

**Comment by cool-raju** [comment]
Hi
We can't see your share pages. you can download the updated version from our git repository. First go to https://github.com/multivendorx/MultiVendorX this link then click on code(right side green box)

**Comment by cool-raju** [comment]
hope this is fixed in your end
