### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by quenecesitasstore** [multivendorx/mvx#234]
I downloaded the pluging and when I try to  activate it it appears a message as fatal error

**Comment by moumitahalder** [comment]
Hi @quenecesitasstore, sorry to hear that you have faced this issue.

Can you please enable the debug mode and share the error message so we can assist you accordingly.

**Comment by quenecesitasstore** [comment]
Hi, thanks, where I can enable the debug mode ?

**Comment by cool-raju** [comment]
please check https://wordpress.org/support/article/debugging-in-wordpress/ this doc
Thanks

**Comment by quenecesitasstore** [comment]
Hi please can you help me i need to disable the vendor dashboard I want it
to be redirected tod My account and not to the dashboard it is possible?

Thanks 😊

**Comment by moumitahalder** [comment]
@quenecesitasstore , do you want to remove vendor dashboard completely?

**Comment by quenecesitasstore** [comment]
Hi yes I want to remove it completely cause or that that redirection goes
directly to my account page and not to the dashboard please 🙏

**Comment by cool-raju** [comment]
Hi,
You can easily change the vendor dashboard page from the dropdown https://scrnli.com/files/8x82FjUS8LKB8D
Thanks

**Comment by cool-raju** [comment]
hope your issue has been resolved
Thanks
