### ISSUE TITLE
MultiVendorX 4.0.1

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#235]
- [x] Vendor Dashboard custom css not working @cool-raju 
- [x] Let admin delete Commission from commission list page @cool-raju  
- [x] Extra field is showing for product-wise commission https://prnt.sc/tR1w4QpfhhQZ
- [x] Bulk CSV download option  is giving black csv https://prnt.sc/RxHRL4_hzxnP @cool-raju 
- [x] Transaction details showing no data : https://fluvid.com/videos/detail/8wKmdCPD19s5-Zoyd @cool-raju 
- [x] Admin is not able to view the transaction details page: https://fluvid.com/videos/detail/oAD7jIPDkQF-vQzkO @cool-raju
- [x] Product type data and commission value is not transferring from WCMp to MVX

**Comment by cool-raju** [comment]
black csv means??? @moumitahalder

**Comment by moumitahalder** [comment]
@cool-raju We have a section that lets admin down commission via csv.

**Comment by cool-raju** [comment]
added
