### ISSUE TITLE
MultiVendorX 4.0.2

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#236]
- [x] - [Commission by product price i](https://doc-0s-8o-chat.googleusercontent.com/downloads/4id2cj1qbm2jb9gabcmo7rgh88/sgdg209eqvpelpl7ql2rujjtag/1666760880000/8bPfcEAAAAE/114724640822285841698/c2NyZWVuLWNhcHR1cmUgKDM1KS53ZWJt?url_type=DOWNLOAD_URL&content_type=video/webm&auto=false&issue_time=1666760884387&group_id=8bPfcEAAAAE&topic_id=QxnOBRdrfvI&message_id=QxnOBRdrfvI&authuser=0&sha_256=eeae6cd379c3b7ea7d4006482ef189e3465351ca49ea38933743687c3fb76017&content_name=screen-capture+(35).webm&nonce=g6vnh2masnefa&user=114724640822285841698&hash=ugp23je0lmhu90ufus2cjsadvs)s not[ working https://multivendorx.com/support-forum/topic/admin-commission-not-working/#post-145001 @cool-raju 
- [x] If you change endpoint URL for question and answer(https://prnt.sc/Qgc3GTNGVY6R), it will show 404 error : https://multivendorx.com/support-forum/topic/new-and-old-endpoints-broken/#post-145117 
- [x] Mark as Read button is not working https://multivendorx.com/support-forum/topic/mark-as-read-button-dont-work/#post-145206 
- [x] Let admin add images or style for announcement and knowledgebase 
- [x] Change the string name https://scrnli.com/files/vWDxael1TjS8Qj

**Comment by moumitahalder** [comment]
@cool-raju please check this for mark as read button https://fluvid.com/videos/detail/Vz3jGIw4APh_mjQKd

**Comment by cool-raju** [comment]
already fixed it @moumitahalder

**Comment by mperochon** [comment]
Hi @cool-raju, I made the test with the latest code and I can still reproduce the issue with the mark as read button.

**Comment by cool-raju** [comment]
hello @mperochon please share a video of your issue along with admin and FTP details. So that we can check from your site.
Thanks

**Comment by mperochon** [comment]
Hello @cool-raju I'm sorry, I cannot share a FTP account because we don't have it.

Please check the video, I'm trying to mark as read a notification generated by the stripe marketplace plugin.

https://user-images.githubusercontent.com/14574344/199456630-0bc17788-6024-4b15-be7b-94770db51adb.mov

**Comment by cool-raju** [comment]
Hi
This was an issue in our previous version. Now there is no issue https://www.loom.com/share/c62f011f0457469f83d0401fbb0a24f2.
Please delete the existing plugin and use current git version of our plugin

**Comment by mperochon** [comment]
Hi @cool-raju Sorry I was busy this week. After made extra test, I needed to clean my chrome cache.... Stupid thing.. Thanks for the fix :)

**Comment by cool-raju** [comment]
ok @mperochon 
Thanks for informing
