### ISSUE TITLE
MultiVendorX 4.0.1 crashes WordPress admin panel

### ISSUE THREAD

**Issue by StefanPeev** [multivendorx/mvx#237]
The activation of MultiVendorX 4.0.1 crashes WordPress admin panel.

**Comment by cool-raju** [comment]
Hi @StefanPeev 
Could you please share your debug log? So that we can check
Thanks

**Comment by cool-raju** [comment]
hi,
Hope your issue has been resolved. If still facing the issue then issue our current git version. If still not fixed then don't hasitate to get back to us
Thanks
