### ISSUE TITLE
MultiVendor Update 4.0.2

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#238]
- [x] Let admin delete questions: https://multivendorx.com/support-forum/topic/new-and-old-endpoints-broken/#post-145704
- [x] Related Product not working: https://multivendorx.com/support-forum/topic/related-producst-dont-appear-anymore-on-the-product-page/#post-145975
- [x] Google map API location not working: https://fluvid.com/videos/detail/xdDvytEek8fnaY1k3
- [x] Commission CSV data missing Sub-Order Number, Products, Data

**Comment by cool-raju** [comment]
second one replied to that specific thread

**Comment by cool-raju** [comment]
Google map API location not working : https://fluvid.com/videos/detail/xdDvytEek8fnaY1k3 >>>
Please enabled the store location module from the module section @moumitahalder
