### ISSUE TITLE
Vendors unable to change the order status 

### ISSUE THREAD

**Issue by tan-hue** [multivendorx/mvx#242]
![image](https://user-images.githubusercontent.com/85879161/200508324-6c607c87-d18e-4f34-bcde-1c66cf7c35b9.png)

vendor dashboard 

![image](https://user-images.githubusercontent.com/85879161/200508903-103cecef-dad2-4ce7-a53e-493d720d74ab.png)

**Comment by cool-raju** [comment]
Please update to the latest version
