### ISSUE TITLE
Activation of MultiVendorX causes critical error and stops the access to Wordpress dashboard

### ISSUE THREAD

**Issue by StefanPeev** [multivendorx/mvx#243]
I deactivated the previous version of the plugin and even deleted the plugin. Then I downloaded the plugin from https://multivendorx.com and tried to activate it but the result was the same. Again I deactivated and deleted the plugin and downloaded and installed it from GitHub - the result is again a critical error when I try to activate the plugin. I see the same issue on your [forum](https://multivendorx.com/support-forum/topic/critical-error-2/). I use all the latest updates of Wordpress, Woocommerce and other plugins.

**Comment by moumitahalder** [comment]
Stefan, sorry to hear that.

As this is site specific issue, so can you please share your site's admin and FTP access in our email i.e. contact@multivendorx.com
Looking for your co-operation regarding the same.

**Comment by cool-raju** [comment]
Please updated to current WordPress version and check again.
Thanks

**Comment by StefanPeev** [comment]
My WordPress version is 6.1. I deleted MultivendorX plugin, I downloaded ZIP from GitHub and I installed manually version 4.0.2 of MultivendorX. The result after activation was the same: MultiVendorX caused critical error and stoped the access to Wordpress dashboard.

**Comment by cool-raju** [comment]
please share the log. @StefanPeev

**Comment by mperochon** [comment]
@cool-raju I'm not sure if it's related, but seems I update the version this morning, I got a fatal error on the website :

> Warning: Attempt to read property "plugin_url" on null in /var/www/html/wordpress/wp-content/plugins/dc-woocommerce-multi-vendor/includes/mvx-core-functions.php on line 7095
> 
> Warning: Attempt to read property "plugin_path" on null in /var/www/html/wordpress/wp-content/plugins/dc-woocommerce-multi-vendor/includes/mvx-core-functions.php on line 7096
> 
> Warning: Attempt to read property "plugin_path" on null in /var/www/html/wordpress/wp-content/plugins/mvx-pro/modules/stripe-marketplace/classes/class-mvx-stripe-marketplace.php on line 341
> 
> Warning: require_once(lib/Stripe/init.php): Failed to open stream: No such file or directory in /var/www/html/wordpress/wp-content/plugins/mvx-pro/modules/stripe-marketplace/classes/class-mvx-stripe-marketplace.php on line 341
> 
> Fatal error: Uncaught Error: Failed opening required 'lib/Stripe/init.php' (include_path='.:/usr/share/php') in /var/www/html/wordpress/wp-content/plugins/mvx-pro/modules/stripe-marketplace/classes/class-mvx-stripe-marketplace.php:341 Stack trace: #0 /var/www/html/wordpress/wp-includes/class-wp-hook.php(308): MVX_Stripe_Marketplace->init() #1 /var/www/html/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #2 /var/www/html/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /var/www/html/wordpress/wp-settings.php(617): do_action() #4 /var/www/html/wordpress/wp-config.php(89): require_once('...') #5 /var/www/html/wordpress/wp-load.php(50): require_once('...') #6 /var/www/html/wordpress/wp-admin/admin.php(34): require_once('...') #7 /var/www/html/wordpress/wp-admin/plugins.php(10): require_once('...') #8 {main} thrown in /var/www/html/wordpress/wp-content/plugins/mvx-pro/modules/stripe-marketplace/classes/class-mvx-stripe-marketplace.php on line 341

**Comment by cool-raju** [comment]
hi,
this might be a plugin conflict. Please check with default woocommerce and multivendorx plugin and default theme
Thanks

**Comment by cool-raju** [comment]
Hi,
As you mentioned on the support forum, your issue is resolved. We are closing this issue
