### ISSUE TITLE
Safari browser issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#246]
https://www.loom.com/share/38a7bd2dcc114122879437d849ed0438

https://multivendorx.com/support-forum/topic/storefront-issues/#post-126302

**Comment by cool-raju** [comment]
we have used html date https://www.w3schools.com/tags/att_input_type_date.asp
As you can see this is supported as per there doc.
Please check your safari verion as mention on the doc
@moumitahalder
