### ISSUE TITLE
Sub order view in order email

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#253]
It would be nice to have the option to display the items ordered and grouped under each vendor suborders, so that it is clear that their order is divided into suborders.
https://multivendorx.com/support-forum/topic/enhancement-request-show-items-grouped-by-suborder-in-customer-new-order-email/#post-108648

**Comment by user-promi** [comment]
For suborder view in order email you need to override the email-order-details.php file (yourtheme/woocommerce/emails/email-order-details.php with this file https://drive.google.com/file/d/1kvCQhaGTypmKy4mXmkDaXLvvgN-ELwNr/view?usp=share_link
