### ISSUE TITLE
Error at the time of accessing products

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#261]
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /customers/6/7/a/hittanynashamn.se/httpd.www/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-product.php:1581 Stack trace: #0 /customers/6/7/a/hittanynashamn.se/httpd.www/wp-includes/class-wp-hook.php(310): MVX_Product->edit_product_cat_commission_fields(Object(WP_Term)) #1 /customers/6/7/a/hittanynashamn.se/httpd.www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #2 /customers/6/7/a/hittanynashamn.se/httpd.www/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /customers/6/7/a/hittanynashamn.se/httpd.www/wp-admin/edit-tag-form.php(256): do_action('product_cat_edi...', Object(WP_Term), 'product_cat') #4 /customers/6/7/a/hittanynashamn.se/httpd.www/wp-admin/term.php(74): require('/customers/6/7/...') #5 {main} thrown in /customers/6/7/a/hittanynashamn.se/httpd.www/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-product.php on line 1581

**Comment by cool-raju** [comment]
fix added on github. please ak d clint for update
