### ISSUE TITLE
Password reset issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#263]
- when I go to look at a vendor profile in the WP Admin Dashboard under MultivendorX->Vendors->Edit Vendor, 
- - the profile image doesn’t show 
- if I try to upload a new one, it automatically resets the password to something I never set and logs out the vendor. 
https://jhn4wdmbd4.vmaker.com/record/96xpdQA9YSAAI423

https://multivendorx.com/support-forum/topic/vendor-profile-image-not-showing-in-admin-password-resets-when-uploading-one/#post-147379

**Comment by cool-raju** [comment]
added
