### ISSUE TITLE
Buddypress settings not working

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#264]
This following settings are not working
- After scrolling down, vendors can choose how they want to sync their shop with BuddyPress. The options are :
My store to BuddyPress– This means members in the vendor’s BuddyPress profile can make purchases from the vendor’s shop directly from the BuddyPress profile of the vendor. Shopping features like cart, order list, and shopping history can be accessed through the BuddyPress profile without being directed to the vendor shop.

- BuddyPress to my Store – Selecting this lets customer’s information about like purchases, Order Id, Shipping Address, and so on be available on the vendor’s shop profile despite the customers placing orders from their BuddyPress profile.
Vendors can then choose what part of their profile they want to sync with the vendor’s shop profile. The sync options are

- Profile Picture – By syncing this option with the shop profile, both the BuddyPress profile and the vendor’s shop profile will display the same picture 

- Cover Picture – By selecting this option the cover photo on the vendor’s shop will be the same as that of his BuddyPress account 
Name – If selected, the vendor name displayed on his shop profile will be the name displayed on his BuddyPress profile

**Comment by cool-raju** [comment]
fixed @moumitahalder
