### ISSUE TITLE
Inventory Issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#274]
**To Recreate The issue**
- When order is placed product stock is reduced by 1 and go out of stock(corect). 
- On wordpress backend when vendor opens the quick preview order window and use the “Completed” button, product stock is increased by 1 and stays on “out of stock” status. https://jhn4wdmbd4.vmaker.com/record/LC8Bt0YdlXMLgSdE
- That doesnt happen when vendor open the product and choose completed status from dropdown.

**Comment by cool-raju** [comment]
added. please check again

**Comment by cool-raju** [comment]
discussed
