### ISSUE TITLE
Admin not able to delet order using "Empty Trash"

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#277]
When admin use “clean trash bin” button in orders he gets and error “sorry you dont have permission to delete that element”. The order is deleted after page reload , only error is showing every time. When admin use the dropdown option “delete forever” there is no error. Checked that also with only woocommerce and multivendorx on storefront.

https://jhn4wdmbd4.vmaker.com/record/NVSCHKDvo9wzZIVZ

**Comment by cool-raju** [comment]
this is a capability issue in your end. no such issue

**Comment by cool-raju** [comment]
fixed
