### ISSUE TITLE
Admin not able to upload vendor logo

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#278]
When we want to update a vendor's profile image (loggued as an admin) :
https://mon.agenda-medecinesdouces.com/wp-admin/admin.php?page=mvx#&submenu=vendor&ID=3&name=vendor-personal
Update goes fine, POST data contains profile URL in "vendor_profile_image", but reloading shows the image is not saved, confirmed in database.

In the update code, mvx_update_vendor(), nothing to use the data sent for the profile image.
There is a hook, mvx_vendor_details_update, but it's not used.
We had to use it to save the profile image.

The image displayed in this page is always empty, because there is nothing in the code to get it.
In mvx_list_of_all_tab_based_settings_field(), the setting 'vendor_profile_image' has an empty value, verified by manually putting values in database.
We used the filter mvx_vendors_tab_routes to set it.

As a vendor, there is nothing to update the profile picture, only store logo or banner.

When we want to change logo or banner, the media window opens but loads no image.
We have no use for the vendor dashboard for now but it will come.
https://jhn4wdmbd4.vmaker.com/record/wupJs8e0U4HfgT7s

**Comment by cool-raju** [comment]
fixed
