### ISSUE TITLE
WPML Issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#280]
** To Recreate **
- Activate WooCommerce and MultiVendorX
- Then Activate WPML and string Translation

At the time of translating the dashbaord page, we are getting this error :

"Fatal error: Uncaught Error: Call to undefined method WP_Textdomain_Registry::reset() in /home/wcmpdemos/public_html/moumita/wp-content/plugins/wpml-string-translation/classes/MO/Hooks/LanguageSwitch.php:139 Stack trace: #0 /home/wcmpdemos/public_html/moumita/wp-content/plugins/wpml-string-translation/classes/MO/Hooks/LanguageSwitch.php(119): WPML\ST\MO\Hooks\LanguageSwitch->resetTranslationAvailabilityInformation() #1 /home/wcmpdemos/public_html/moumita/wp-content/plugins/wpml-string-translation/classes/MO/Hooks/LanguageSwitch.php(73): WPML\ST\MO\Hooks\LanguageSwitch->changeMoObjects('bn_BD') #2 /home/wcmpdemos/public_html/moumita/wp-content/plugins/wpml-string-translation/classes/MO/Hooks/LanguageSwitch.php(48): WPML\ST\MO\Hooks\LanguageSwitch->switchToLocale('bn_BD') #3 /home/wcmpdemos/public_html/moumita/wp-includes/class-wp-hook.php(310): WPML\ST\MO\Hooks\LanguageSwitch->languageHasSwitched('bn') #4 /home/wcmpdemos/public_html/moumita/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #5 /home/wc in /home/wcmpdemos/public_html/moumita/wp-content/plugins/wpml-string-translation/classes/MO/Hooks/LanguageSwitch.php on line 139"

**Comment by cool-raju** [comment]
ita default
