### ISSUE TITLE
Elementor Widget

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#312]
** To Recreate **
- Edit the Single SHop page of WooCommerce
- Add Sidebar
- Select the theme's widget name where you have added mvx widget
- Now add these 3 widgets of MVX via Apprence >> Widget, you can see that these 3 are not working
1. MVX Vendor’s Store Location > NOTHING DISPLAY ON THE PAGE (The Google Api are ok)
2. MVX Vendor’s Policies > NOTHING DISPLAY ON THE PAGE
3. MVX Vendor’s Recent Product > NOTHING DISPLAY ON THE PAGE

**Comment by cool-raju** [comment]
discussed. no such issue
