### ISSUE TITLE
Cannot install MarketPlace X to replace My Multivendor Addon on Wordpress

### ISSUE THREAD

**Issue by AfandeeLB** [multivendorx/mvx#321]
I tried many times to download and install your new version to replace the old one I have but couldn't succeed after Manu attempts!

Can you help please

**Comment by moumitahalder** [comment]
Hi @AfandeeLB , not to worry.
If you are referring to shifting from WCMp to MultiendorX, then I would recommend you do the updation in the staging site first. 
Download the Multivendor plugin from here: https://downloads.wordpress.org/plugin/dc-woocommerce-multi-vendor.4.0.9.zip
You can simply delete the current WCMp plugin and install the downloaded plugin.
To know more, please check this : https://www.youtube.com/watch?v=E6ZPznJ2Hew
