### ISSUE TITLE
MultiVendorX >> Vendor

### ISSUE THREAD

**Issue by tan-hue** [multivendorx/mvx#322]
Under Bulk action, we can only delete the vendors. whereas all the statuses should be present. ( Approve, reject, suspended, pending) 

https://watch.screencastify.com/v/cSHb6Ct4sIKgfXWaZjrw

**Comment by tan-hue** [comment]
bulk status is not changing to Approve from pending, reject, suspended,

**Comment by cool-raju** [comment]
create a new vendor and check again
.if still not fixed then make a complete video of issue

**Comment by moumitahalder** [comment]
@tan-hue any update?
