### ISSUE TITLE
Cart Page error 

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#363]
- Enable the "Display Seller" tab
- Add multiple products from different vendors 
- Goto checkout page https://tinyurl.com/2c7ch4eg
- You can see this error : 
`Fatal error: Uncaught ValueError: Path cannot be empty in /home/multivendordemo/public_html/test/moumita/wp-content/plugins/woocommerce/includes/wc-core-functions.php:345 Stack trace: #0 /home/multivendordemo/public_html/test/moumita/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-cart.php(99): wc_get_template() #1 /home/multivendordemo/public_html/test/moumita/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Cart::output() #2 /home/multivendordemo/public_html/test/moumita/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(85): WC_Shortcodes::shortcode_wrapper() #3 /home/multivendordemo/public_html/test/moumita/wp-includes/shortcodes.php(355): WC_Shortcodes::cart() #4 [internal function]: do_shortcode_tag() #5 /home/multivendordemo/public_html/test/moumita/wp-includes/shortcodes.php(227): preg_replace_callback() #6 /home/multivendordemo/public_html/test/moumita/wp-includes/class-wp-hook.php(308): do_shortcode() #7 /home/multivendordemo/public_html/test/moumita/wp-includes/plugin.php(205): WP_Hook->apply_filters() #8 /home/multivendordemo/public_html/test/moumita/wp-includes/blocks/post-content.php(54): apply_filters() #9 /home/multivendordemo/public_html/test/moumita/wp-includes/class-wp-block.php(258): render_block_core_post_content() #10 /home/multivendordemo/public_html/test/moumita/wp-includes/class-wp-block.php(244): WP_Block->render() #11 /home/multivendordemo/public_html/test/moumita/wp-includes/blocks.php(1051): WP_Block->render() #12 /home/multivendordemo/public_html/test/moumita/wp-includes/blocks.php(1089): render_block() #13 /home/multivendordemo/public_html/test/moumita/wp-includes/block-template.php(240): do_blocks() #14 /home/multivendordemo/public_html/test/moumita/wp-includes/template-canvas.php(12): get_the_block_template_html() #15 /home/multivendordemo/public_html/test/moumita/wp-includes/template-loader.php(106): include('...') #16 /home/multivendordemo/public_html/test/moumita/wp-blog-header.php(19): require_once('...') #17 /home/multivendordemo/public_html/test/moumita/index.php(17): require('...') #18 {main} thrown in /home/multivendordemo/public_html/test/moumita/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 345`

**Comment by cool-raju** [comment]
fixed
