### ISSUE TITLE
Withdrawal request to Admin from Vendor by BAC change

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#385]
This mail should be triggered only when the vendor is asking for withdwal 
; https://prnt.sc/DZvTertSXiIv

As per the current flow, this is also sending the mail when admin manually marking a order as paid when vendor has selected BAC

**Comment by Sangi0** [comment]
https://multivendorx.com/support-forum/topic/disable-automatic-disbursement-and-dashboard-problem/#post-192155
