### ISSUE TITLE
Issue frontend for [mvx_vendorslist] shortcode

### ISSUE THREAD

**Issue by Albinoty** [multivendorx/mvx#389]
When I tried to display vendors on a specific page with shortcode **[mvx_vendorslist]**, product images doesn't appear correctly.

Screenshot: https://prnt.sc/BXw_RFJ8q1GT

**Comment by cool-raju** [comment]
Hi @Albinoty ,
We have checked all the default themes. We didn't face any such issue. This might be your theme issue.
Thanks
