### ISSUE TITLE
mvx table rate error

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#398]
https://prnt.sc/tra44gWGt8YP

**Comment by cool-raju** [comment]
tested

**Comment by cool-raju** [comment]
@please test it
@Sangi0 @moumitahalder

**Comment by Sangi0** [comment]
Deprecated: Required parameter $package follows optional parameter $rates in /home/multivendordemo/public_html/test/test1/wp-content/plugins/dc-woocommerce-multi-vendor/packages/mvx-tablerate/mvx-tablerate.php on line 357    
This comes after activating MultiVendorX with the fix .

**Comment by moumitahalder** [comment]
same error on my end. @cool-raju 
Also now module page is not opening : https://multivendordemo.com/test/moumita/wp-admin/admin.php?page=mvx#&submenu=modules

**Comment by cool-raju** [comment]
tested

**Comment by cool-raju** [comment]
please test it again
@Sangi0 @moumitahalder

**Comment by Sangi0** [comment]
test done , no issue
