### ISSUE TITLE
Issue with suspension of a vendor 

### ISSUE THREAD

**Issue by Sangi0** [multivendorx/mvx#399]
Once the admin suspends a vendor , the status of the vendor becomes suspended . After that if the vendor approves the suspended vendor the approval does not work .The vendor still remains suspended.
But a mail is sent to the vendor informing that the admin has approved his application and application status is now approved .
https://watch.screencastify.com/v/oBmfxgBiQ54BEjXLWpUs

**Comment by moumitahalder** [comment]
Kundan Assigned
