### ISSUE TITLE
Vendor Unbale to make withdraw request 

### ISSUE THREAD

**Issue by ikishorkumar** [multivendorx/mvx#409]
Warnings 
Warning: Undefined property: stdClass::$batch_header in /wp-content/plugins/dc-woocommerce-multi-vendor/classes/gateways/class-mvx-gateway-paypal-payout.php on line 161  

Warning: Attempt to read property "batch_status" on null in public/wp-content/plugins/dc-woocommerce-multi-vendor/classes/gateways/class-mvx-gateway-paypal-payout.php on line 161

private function process_paypal_payout() {
    $api_authorization = "Authorization: {$this->token_type} {$this->access_token}";
    $amount_to_pay = round($this->get_transaction_total() - $this->transfer_charge($this->transaction_mode) - $this->gateway_charge(), 2);
    $note = sprintf(__('Total commissions earned from %1$s as at %2$s on %3$s', 'multivendorx'), get_bloginfo('name'), date('H:i:s'), date('d-m-Y'));
    $request_params = '{
        "sender_batch_header": {
            "sender_batch_id":"' . uniqid() . '",
            "email_subject": "You have a payment",
            "recipient_type": "EMAIL"
        },
        "items": [
            {
                "recipient_type": "EMAIL",
                "amount": {
                    "value": ' . $amount_to_pay . ',
                    "currency": "' . $this->currency . '"
                },
                "receiver": "' . $this->reciver_email . '",
                "note": "' . $note . '",
                "sender_item_id": "' . $this->vendor->id . '"
            }
        ]
    }';

    $response = wp_remote_post( $this->api_endpoint, apply_filters( "mvx_payment_gateway_{$this->id}_http_process", array(
        'timeout' => 60,
        'headers' => array(
            'Content-Type' => 'application/json',
            'Authorization' => "$this->token_type $this->access_token"
        ),
        'sslverify' => apply_filters( 'https_local_ssl_verify', false ),
        'httpversion' => '1.1',
        'body' => $request_params
    ) ) );

    // Check for error during API request
    if ( is_wp_error( $response ) ) {
        $this->add_commission_note($this->commissions, __('Payment failed', 'multivendorx'));
        return false;
    }

    // Extract the response details
    $result_array = json_decode(wp_remote_retrieve_body( $response ));

    // Check if the batch_header property exists
    if ( isset( $result_array->batch_header ) && isset( $result_array->batch_header->batch_status ) ) {
        $batch_status = $result_array->batch_header->batch_status;
        
        if ( $this->payout_mode === 'true' ) {
            $transaction_status = is_array($result_array->items) ? $result_array->items[0]->transaction_status : '';
            if ( $batch_status === 'SUCCESS' && $transaction_status === 'SUCCESS' ) {
                return $result_array;
            } else {
                doProductVendorLOG(json_encode($result_array));
                $this->add_commission_note($this->commissions, __('Payment failed', 'multivendorx'));
                return false;
            }
        } else {
            $batch_payout_status = apply_filters('mvx_paypal_payout_batch_status', array('PENDING', 'PROCESSING', 'SUCCESS', 'NEW'));
            if ( in_array($batch_status, $batch_payout_status) ) {
                return $result_array;
} else {
doProductVendorLOG(json_encode($result_array));
$this->add_commission_note($this->commissions, __('Payment failed', 'multivendorx'));
return false;
}
}
} else {
// Handle the case when the batch_header property is undefined or null
$this->add_commission_note($this->commissions, __('Payment failed', 'multivendorx'));
return false;
}
}

In this updated version of the `process_paypal_payout()` method, I've added error handling to check for any issues during the API request. If an error occurs during the request, it will log the error and return `false`. Additionally, I've included a check to verify if the `batch_header` property exists in the response before accessing its `batch_status` property. If the `batch_header` property is undefined or null, it will handle the error by logging it and returning `false`.

By implementing these changes, the warning and error messages should be resolved, and the "Oops! Something went wrong, please try again later" error message should no longer appear.

Commission log on owner site : 

Payment failed

2023-06-09 16:03:33
Error: We're sorry, but your PayPal account isn't currently eligible to send mass payments. Please contact either PayPal Customer Service or your account manager.

2023-06-09 15:59:57
Payment failed

2023-06-09 15:58:58
Payment failed

2023-06-09 15:58:50
Payment failed

2023-06-09 15:54:52

**Comment by Sangi0** [comment]
We have checked this on our end . There should not be any such issue if you have configured PayPal payout correctly . Kindly fetch the credentials accordingly . You can go through our doc for your reference https://multivendorx.com/docs/knowledgebase/paypal-payout/
