### ISSUE TITLE
Approve/reject button not working

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#416]
- Approve/reject button not working https://prnt.sc/6JWlZKIwILiZ
https://www.loom.com/share/55c590247b7b4f8fa1dc753918959517

**Comment by Sangi0** [comment]
The button does work for approving a suspended vendor but does not work for approving a pending vendor https://watch.screencastify.com/v/cuxkar1a3oQavY20QGS9

**Comment by kndnsow** [comment]
test the fix @Sangi0

**Comment by Sangi0** [comment]
Tested the flow. Working fine
