### ISSUE TITLE
DevTools failed load source map issue 

### ISSUE THREAD

**Issue by Sangi0** [multivendorx/mvx#452]
DevTools failed to load source map: Could not load content for https://thehamptonsfarmersmarket.com/wp-content/plugins/dc-woocommerce-multi-vendor/lib/popper/popper.min.js.map: Unexpected token ‘<‘, “<!DOCTYPE “… is not valid JSON

**Comment by moumitahalder** [comment]
@Sangi0 what is the issue here?

**Comment by Sangi0** [comment]
There is a DOCTYPE added in popper.min.js.map of MultiVendorX.
