### ISSUE TITLE
Add support for additional content in new vendor account mail

### ISSUE THREAD

**Issue by Sangi0** [multivendorx/mvx#532]
Go to Admin dashboard>>WooCommerce >>Emails>>New vendor account here in the additional content text box https://prnt.sc/uOwGTpUQ8ISH if we add any text that does not reflect on the vendor new account mail. We do not have support for this currently. 

But need to add support there so that the text will be reflected in the mails.

**Comment by abhirup97** [comment]
https://github.com/multivendorx/MultiVendorX/pull/535
