### ISSUE TITLE
Issue with the refund management flow 

### ISSUE THREAD

**Issue by Sangi0** [multivendorx/mvx#763]
1. The vendor and the admin is refunding the order amount to the customers but the commission status in the commission submenu of MultiVendorX is not getting updated accordingly. 
2. We need to add modification where if the order is getting refunded from the main order page then that details should get updated in suborder details page as well. 

https://multivendorx.com/support-forum/topic/refund-feature-not-working-in-single-vendors-order/#post-220419

**Comment by moumitahalder** [comment]
When admin goes to main order -> modifies any order related data i.e. refund too, the same should be reflected for sub order

When Sub order data is updated, the commission data should also be updated. So, admin, vendor and customer can view the same from their end.
