### ISSUE TITLE
Error while adding product from the admin dashboard 

### ISSUE THREAD

**Issue by Sangi0** [multivendorx/mvx#792]
Uncaught TypeError: Cannot access offset of type string on string in /var/www/wordpress/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-product.php:792

**Comment by moumitahalder** [comment]
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /home3/lkmcjsmy/public_html/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-product.php:792 Stack trace: #0 /home3/lkmcjsmy/public_html/wp-includes/class-wp-hook.php(324): MVX_Product->output_vendor_tab('') #1 /home3/lkmcjsmy/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #2 /home3/lkmcjsmy/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /home3/lkmcjsmy/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php(54): do_action('woocommerce_pro...') #4 /home3/lkmcjsmy/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(33): include('/home3/lkmcjsmy...') #5 /home3/lkmcjsmy/public_html/wp-admin/includes/template.php(1456): WC_Meta_Box_Product_Data::output(Object(WP_Post), Array) #6 /home3/lkmcjsmy/public_html/wp-admin/edit-form-advanced.php(723): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post)) #7 /home3/lkmcjsmy/public_html/wp-admin/post.php(206): require('/home3/lkmcjsmy...') #8 {main} thrown in /home3/lkmcjsmy/public_html/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-product.php on line 792
