### ISSUE TITLE
Broken documentation link in Commissions page

### ISSUE THREAD

**Issue by TheIanM** [multivendorx/mvx#801]
on the wp-admin/admin.php?page=mvx#&submenu=settings&name=commissions page the article linked in the quoted section below: 
> about Select how you want the commission to be split. If you are not sure about how to setup commissions and payment options in your marketplace, kindly read this [article](https://multivendorx.com/doc/knowledgebase/payments/) before proceeding.

links to https://multivendorx.com/doc/knowledgebase/payments/ which 404s. Reviewing your documentation it would appear that https://multivendorx.com/docs/knowledgebase/types-of-commission/ is the correct article that should be linked instead.

**Comment by moumitahalder** [comment]
Hi @TheIanM, 

Thank you for bringing this to our attention.

We have already updated the link on our end. If you have any other concerns or need further assistance, please let us know.
