### ISSUE TITLE
Getting non-empty vendor categories

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#825]
Is it possible to get non-empty categories for a specific vendor from wcmp rest api? I mean the categories in which this vendor has products.

It would be even better to get, for example, the first(or second, third…) ten non-empty vendor categories with 10 products in each of categories.

**Comment by Sangi0** [comment]
The issue is already filed earlier here https://github.com/multivendorx/MultiVendorX/issues/587.
